# 端口
server:
    port: 8888
spring:
    application:
        name: hr-backend
# 数据库配置
    datasource:
        url: jdbc:mysql://localhost:3306/hr-system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
#    sql:
#        init:
#            schema-locations: classpath:db/schema-h2.sql
#            data-locations: classpath:db/data-h2.sql
#            mode: always

    data:
        redis:
            host: 127.0.0.1
            port: 6379
            password: 123456

# swagger 调试工具
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true

springdoc:
    default-flat-param-object: true
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        - group: 'default'
          paths-to-match: '/**'
          packages-to-scan: com.lss

knife4j:
    enable: true
    setting:
        language: zh_cn

